### For Postgres use the following: ####
#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#
#development:
#  <<: *default
#  database: TuneCoreAlbumIndex_development
#  username: tunecorealbumindex
#  password: tunecorealbumindexpass
#
#test:
#  <<: *default
#  database: TuneCoreAlbumIndex_test
#  username: tunecorealbumindex
#  password: tunecorealbumindexpass
#
#production:
#  <<: *default
#  database: TuneCoreAlbumIndex_production
#  username: tunecorealbumindex
#  password: <%= ENV['TUNECOREALBUMINDEX_DATABASE_PASSWORD'] %>

#### For MySql, use the following: ####
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: TuneCoreAlbumIndex_development

test:
  <<: *default
  database: TuneCoreAlbumIndex_test

production:
  <<: *default
  database: TuneCoreAlbumIndex_production
  username: TuneCoreAlbumIndex
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>